
Loading dataset...
batch_size = 16
learning rate = 0.0001
train_size = 65372
validation_size = 18677
test_size = 9340
Data load complete!
Initializing model....
Traceback (most recent call last):
  File "SampleCNN_main.py", line 117, in <module>
    state = init_state(model, next(iter(train_dataloader))[0].shape, jax.random.PRNGKey(353), lr)
  File "SampleCNN_main.py", line 32, in init_state
    params = model.init({'params': key, 'dropout':key}, jnp.ones(shape))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1273, in init
    _, v_out = self.init_with_output(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1229, in init_with_output
    return init_with_output(
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 897, in wrapper
    return apply(fn, mutable=mutable, flags=init_flags)({}, *args, rngs=rngs,
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 865, in wrapper
    y = fn(root, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1647, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/anthonypark6904/module/model.py", line 88, in __call__
    x = nn.sigmoid(nn.Dense(30)(x))
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/linear.py", line 186, in __call__
    kernel = self.param('kernel',
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 997, in param
    v = self.scope.param(name, init_fn, *init_args)
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 775, in param
    value = init_fn(self.make_rng('params'), *init_args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/nn/initializers.py", line 265, in init
    fan_in, fan_out = _compute_fans(named_shape, in_axis, out_axis, batch_axis)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/nn/initializers.py", line 173, in _compute_fans
    receptive_field_size = shape.total / in_size / out_size / batch_size
jax._src.traceback_util.UnfilteredStackTrace: ZeroDivisionError: division by zero
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "SampleCNN_main.py", line 117, in <module>
    state = init_state(model, next(iter(train_dataloader))[0].shape, jax.random.PRNGKey(353), lr)
  File "SampleCNN_main.py", line 32, in init_state
    params = model.init({'params': key, 'dropout':key}, jnp.ones(shape))
  File "/home/anthonypark6904/module/model.py", line 88, in __call__
    x = nn.sigmoid(nn.Dense(30)(x))
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/linear.py", line 186, in __call__
    kernel = self.param('kernel',
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/nn/initializers.py", line 265, in init
    fan_in, fan_out = _compute_fans(named_shape, in_axis, out_axis, batch_axis)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/nn/initializers.py", line 173, in _compute_fans
    receptive_field_size = shape.total / in_size / out_size / batch_size
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "SampleCNN_main.py", line 117, in <module>
    state = init_state(model, next(iter(train_dataloader))[0].shape, jax.random.PRNGKey(353), lr)
  File "SampleCNN_main.py", line 32, in init_state
    params = model.init({'params': key, 'dropout':key}, jnp.ones(shape))
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1273, in init
    _, v_out = self.init_with_output(
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1229, in init_with_output
    return init_with_output(
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 897, in wrapper
    return apply(fn, mutable=mutable, flags=init_flags)({}, *args, rngs=rngs,
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 865, in wrapper
    y = fn(root, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 1647, in scope_fn
    return fn(module.clone(parent=scope), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/home/anthonypark6904/module/model.py", line 88, in __call__
    x = nn.sigmoid(nn.Dense(30)(x))
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 361, in wrapped_module_method
    return self._call_wrapped_method(fun, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 657, in _call_wrapped_method
    y = fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/linear.py", line 186, in __call__
    kernel = self.param('kernel',
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/module.py", line 997, in param
    v = self.scope.param(name, init_fn, *init_args)
  File "/usr/local/lib/python3.8/dist-packages/flax/core/scope.py", line 775, in param
    value = init_fn(self.make_rng('params'), *init_args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/nn/initializers.py", line 265, in init
    fan_in, fan_out = _compute_fans(named_shape, in_axis, out_axis, batch_axis)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/nn/initializers.py", line 173, in _compute_fans
    receptive_field_size = shape.total / in_size / out_size / batch_size
jax._src.traceback_util.UnfilteredStackTrace: ZeroDivisionError: division by zero
The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.
--------------------
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "SampleCNN_main.py", line 117, in <module>
    state = init_state(model, next(iter(train_dataloader))[0].shape, jax.random.PRNGKey(353), lr)
  File "SampleCNN_main.py", line 32, in init_state
    params = model.init({'params': key, 'dropout':key}, jnp.ones(shape))
  File "/home/anthonypark6904/module/model.py", line 88, in __call__
    x = nn.sigmoid(nn.Dense(30)(x))
  File "/usr/local/lib/python3.8/dist-packages/flax/linen/linear.py", line 186, in __call__
    kernel = self.param('kernel',
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/nn/initializers.py", line 265, in init
    fan_in, fan_out = _compute_fans(named_shape, in_axis, out_axis, batch_axis)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/nn/initializers.py", line 173, in _compute_fans
    receptive_field_size = shape.total / in_size / out_size / batch_size
ZeroDivisionError: division by zero